// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_PRESCRIPTIONS = "GET_PRESCRIPTIONS";


// Add Prescription

export const ADD_NEW_PRESCRIPTION = "ADD_NEW_PRESCRIPTION";
export const ADD_PRESCRIPTION_SUCCESS = "ADD_PRESCRIPTION_SUCCESS";
export const ADD_PRESCRIPTION_FAIL = "ADD_PRESCRIPTION_FAIL";

// Edit Prescription

export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const UPDATE_PRESCRIPTION_SUCCESS = "UPDATE_PRESCRIPTION_SUCCESS";
export const UPDATE_PRESCRIPTION_FAIL = "UPDATE_PRESCRIPTION_FAIL";

// Delete Prescription

export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";
export const DELETE_PRESCRIPTION_SUCCESS = "DELETE_PRESCRIPTION_SUCCESS";
export const DELETE_PRESCRIPTION_FAIL = "DELETE_PRESCRIPTION_FAIL";

