// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_USERS = "GET_USERS";
export const GET_PATIENT = "GET_PATIENT";
