// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ASSESSMENTS = "GET_ASSESSMENTS";

/**
 * Delete ASSESSMENT
 */
export const DELETE_ASSESSMENT = "DELETE_ASSESSMENT";
export const DELETE_ASSESSMENT_SUCCESS = "DELETE_ASSESSMENT_SUCCESS";
export const DELETE_ASSESSMENT_FAIL = "DELETE_ASSESSMENT_FAIL";

/**
 * Add ASSESSMENT
 */
export const ADD_NEW_ASSESSMENT = "ADD_NEW_ASSESSMENT";
export const ADD_ASSESSMENT_SUCCESS = "ADD_ASSESSMENT_SUCCESS";
export const ADD_ASSESSMENT_FAIL = "ADD_ASSESSMENT_FAIL";

/**
 * Edit ASSESSMENT
 */
export const UPDATE_ASSESSMENT = "UPDATE_ASSESSMENT";
export const UPDATE_ASSESSMENT_SUCCESS = "UPDATE_ASSESSMENT_SUCCESS";
export const UPDATE_ASSESSMENT_FAIL = "UPDATE_ASSESSMENT_FAIL";
