// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_COURSES = "GET_COURSES";
export const GET_ORDERS = "GET_ORDERS";
export const GET_MANUFACTURERS = "GET_MANUFACTURERS";
export const GET_CUSTOMERS = "GET_CUSTOMERS";

/**
 * Delete COURSE
 */
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

/**
 * Add COURSE
 */
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

/**
 * Edit COURSE
 */
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";
